import { attachScopes, createFilter } from '@rollup/pluginutils';
import { walk } from 'estree-walker';

/**
 * @param {import('estree').Program} ast generated by rollup
 * @returns {boolean} injectable
 */
const injectProcess = (ast) => {
  let flag = false;
  let scope = attachScopes(ast, 'scope');
  walk(ast, {
    enter(node) {
      if (node.scope) {
        scope = node.scope;
      }
      if (flag) {
        this.skip();
        return;
      }
      if (!scope.contains('process') && node.type === 'Identifier' && node.name === 'process') {
        flag = true;
      }
    },
    leave(node) {
      if (node.scope) {
        scope = scope.parent;
      }
    },
  });
  return flag;
};

export default injectProcess;
